base_url = "https://sidechain-magazine.github.io/"
title = "SIDECHAIN"
theme = "terminus"
build_search_index = false
compile_sass = true

[markdown]
highlight_code = true

[extra]
color_scheme = "tokyo-night"

main_menu = [
	{ name = "articles", url = "articles", trailing_slash = true },
]
