base_url = "https://sidechain-magazine.github.io/"
title = "SIDECHAIN"
theme = "terminus"
build_search_index = false
compile_sass = true

taxonomies = [
	{ name = "installments", feed = true },
	{ name = "authors" },
]

[markdown]
highlight_code = true

[extra]
color_scheme = "nord"
color_scheme_switcher = true

main_menu = [
	{ name = "about", url = "about" },
	{ name = "articles", url = "articles", trailing_slash = true },
	{ name = "installments", url = "installments", trailing_slash = true },
	{ name = "authors", url = "authors", trailing_slash = true },
]
